#! /bin/sh
killall -q polybar
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done
polybar bingus &
setxkbmap gb &
nitrogen --restore &
picom &

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3

bspc config border_width         3
bspc config window_gap           8
bspc config normal_border_color "#11111b"
bspc config focused_border_color "#eba0ac"

bspc config border_radius 10
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
